version: '3'

services:
  app:
    image: bavuongco10/datacloud-meteor
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 5000:80
    environment:
      - MONGO_URL=mongodb://mongo-db:27017/meteor
      - ROOT_URL=http://3.222.225.23.xip.io:5000
    container_name: datacloud-meteor-container
    links:
      - mongo-db
    networks:
      - mongo
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:27017"]
      interval: 30s
      timeout: 10s
      retries: 5

  mongo-db:
    image: mongo:4
    container_name: pnyx-app-mongo
    ports:
      - 27017:27017
    command: mongod --smallfiles --quiet --logpath=/dev/null
    networks:
      - mongo

networks:
  mongo:


